{
    'name': 'Vex Store Syncronizer',
    'version': '16.0.0.2',
    'description': '',
    'summary': '',
    'author': 'Vex Soluciones',
    'website': 'https://www.vexsoluciones.com',
    'license': 'OPL-1',
    'category': 'Uncategorized',
    'depends': [
        'base',
        'stock',
        'sale_management',
        'l10n_latam_base',
    ],
    'data': [
        'data/vex_cron.xml',
        # 'data/vex_data_resapi_list.xml',
        'data/vex_data_config_settings.xml',
        'data/stock_location_data.xml',
        'menus/menu.xml',
        'security/ir_model_access.xml',
        'views/vex_soluciones_instance_view.xml',
        # 'views/vex_soluciones_restapi_list.xml',
        'views/vex_soluciones_config_settings_view.xml',
        'views/vex_soluciones_product_inherit_view.xml',
        'views/vex_soluciones_product_attribute_value_inherit_view.xml',
        'views/vex_soluciones_product_attribute_inherit_view.xml',
        'wizards/vex_soluciones_action.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vex-store-syncronizer/static/src/js/gridstack-all.js',
            'vex-store-syncronizer/static/src/xml/vex-dashboard.xml',
            'vex-store-syncronizer/static/src/js/vex-dashboard.js',
            'vex-store-syncronizer/static/src/css/vex_instance.css',
            'vex-store-syncronizer/static/src/js/vex_instance_form_view.js',
            'vex-store-syncronizer/static/src/css/gridstack.css',
            'vex-store-syncronizer/static/src/css/gridstack-extra.css',
        ],
    },
    'demo': [],
    'auto_install': False,
    'application': False,
}