COUNTRIES = [
    ('MLM', 'Mexico'),
    ('MLV', 'Venezuela'),
    ('MLB', 'Brasil'),
    ('MPE', 'Perú'),
    #('MCU', 'Cuba'),
    ('MNI', 'Nicaragua'),
    ('MRD', 'Dominicana'),
    ('MCO', 'Colombia'),
    ('MCR', 'Costa Rica'),
    ('MBO', 'Bolivia'),
    ('MHN', 'Honduras'),
    ('MLC', 'Chile'),
    ('MGT', 'Guatemala'),
    ('MEC', 'Ecuador'),
    ('MPY', 'Paraguay'),
    ('MPA', 'Panamá'),
    ('MSV', 'El Salvador'),
    ('MLA', 'Argentina'),
    ('MLU', 'Uruguay')
]

COUNTRIES_DOMINIO = {
    'MLM': 'mx',
    'MLV': 've',
    'MLB': 'br',
    'MPE': 'pe',
    #'MCU': 'cu',
    'MNI': 'ni',
    'MRD': 'do',
    'MCO': 'co',
    'MCR': 'cr',
    'MBO': 'bo',
    'MHN': 'hn',
    'MLC': 'cl',
    'MGT': 'gt',
    'MEC': 'ec',
    'MPY': 'py',
    'MPA': 'pa',
    'MSV': 'sv',
    'MLA': 'ar',
    'MLU': 'uy'
}

CURRENCIES = [
    ('ARS', 'Peso argentino'),
    ('BOB', 'Boliviano'),
    ('BRL', 'Real'),
    ('CLF', 'Unidad de Fomento'),
    ('CLP', 'Peso Chileno'),
    ('COP', 'Peso colombiano'),
    ('CRC', 'Colones'),
    ('CUC', 'Peso Cubano Convertible'),
    ('CUP', 'Peso Cubano'),
    ('DOP', 'Peso Dominicano'),
    ('EUR', 'Euro'),
    ('GTQ', 'Quetzal Guatemalteco'),
    ('HNL', 'Lempira'),
    ('MXN', 'Peso Mexicano'),
    ('NIO', 'Córdoba'),
    ('PAB', 'Balboa'),
    ('PEN', 'Soles'),
    ('PYG', 'Guaraní'),
    ('USD', 'Dólar'),
    ('UYU', 'Peso Uruguayo'),
    ('VEF', 'Bolivar fuerte'),
    ('VES', 'Bolivar Soberano')]